[package]
name = "mewe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "*", features = ["derive", "color"] }
reqwest = { version = "*", features = ["blocking"] }
scraper = "*"
tokio = { version = "*", features = ["full"] }
