[package]
name = "mewe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.3", features = ["derive", "color"] }
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["blocking"] }
scraper = "0.17.1"
tokio = "1.32.0"
